"""Supervisor pure core (C2 split into a package).

The control discipline that runs the villa as one organism — kept import-pure
(no `homeassistant` imports) so it is fully unit-testable. Split into:
`arbiter` (reconcile/merge/lever-keys) · `control_law` (band/fan/duty/coalesce/PV)
· `thermal` (RLS/blend) · `model` (HouseState) · `planner` (run-plan/sim/precool/
solar/plan-view — the home for the F4c unified planner) · `returnhome` (#8 core).

Everything is re-exported here so `from ..supervisor import X` keeps working.
"""
from __future__ import annotations

from .arbiter import (
    BLOCCO_BLOCK,
    BLOCCO_LEVER,
    BLOCCO_RELEASE,
    DEFAULT_MAX_REASSERTS,
    DEFAULT_OVERRIDE_BACKOFF,
    DEFAULT_SETPOINT_TOLERANCE,
    LeverState,
    ReconcileResult,
    TRANSIENT_STATES,
    cover_lever,
    fan_lever,
    merge_desired,
    preset_lever,
    reconcile,
    switch_lever,
    temperature_lever,
    values_match,
)
from .thermal import (
    ParamBounds,
    ThermalParams,
    _clamp,
    abc_confidence,
    blend_params,
    estimate_rate,
    k_confidence,
    rls_capacity_update,
    rls_passive_update,
    seed_params,
)
from .returnhome import (
    RETURN_PRECOND,
    RETURN_WAITING,
    ReturnRoom,
    return_decision,
    return_eta,
    return_lead_time,
)
from .control_law import (
    BandState,
    CenterComposition,
    DutyState,
    EnergyPrecoolDecision,
    PRECOOL_BANK,
    PRECOOL_COAST,
    PRECOOL_HOLD,
    RegimeState,
    band_step,
    capacity_fan,
    coalesce_phase,
    compose_center,
    cooling_effectiveness,
    cooling_load,
    duty_decision,
    energy_precool_decision,
    fan_level,
    in_window,
    run_rest_durations,
)
from .model import (
    CoverInfo,
    HouseState,
    ZoneSnapshot,
    _SEASON_SUMMER,
    _is_cooling_leader,
    _is_free_cooling,
    active_cooling_leaders,
)
from .planner import (
    HouseLoad,
    PlanView,
    REGIME_LOW,
    REGIME_MEDIUM,
    REGIME_PEAK,
    RoomParams,
    RoomTrajectory,
    RunPlan,
    TrajPoint,
    ZonePlan,
    _downsample,
    _forecast_temp_at,
    _plan_summary,
    _solar_at,
    build_plan,
    build_room_plans,
    clear_sky_solar,
    house_load_index,
    peak_window,
    plan_run,
    schedule_precool,
    select_regime,
    simulate_room,
    solar_curve_v2,
    solar_forecast_curve,
    solar_nowcast_bias,
)

__all__ = [
    "BLOCCO_BLOCK",
    "BLOCCO_LEVER",
    "BLOCCO_RELEASE",
    "BandState",
    "CenterComposition",
    "CoverInfo",
    "DEFAULT_MAX_REASSERTS",
    "DEFAULT_OVERRIDE_BACKOFF",
    "DEFAULT_SETPOINT_TOLERANCE",
    "DutyState",
    "EnergyPrecoolDecision",
    "HouseLoad",
    "HouseState",
    "LeverState",
    "PRECOOL_BANK",
    "PRECOOL_COAST",
    "PRECOOL_HOLD",
    "ParamBounds",
    "PlanView",
    "REGIME_LOW",
    "REGIME_MEDIUM",
    "REGIME_PEAK",
    "RETURN_PRECOND",
    "RETURN_WAITING",
    "ReconcileResult",
    "RegimeState",
    "ReturnRoom",
    "RoomParams",
    "RoomTrajectory",
    "RunPlan",
    "TRANSIENT_STATES",
    "ThermalParams",
    "TrajPoint",
    "ZonePlan",
    "ZoneSnapshot",
    "_SEASON_SUMMER",
    "_clamp",
    "_downsample",
    "_forecast_temp_at",
    "_is_cooling_leader",
    "_is_free_cooling",
    "_plan_summary",
    "_solar_at",
    "abc_confidence",
    "active_cooling_leaders",
    "band_step",
    "blend_params",
    "build_plan",
    "build_room_plans",
    "capacity_fan",
    "clear_sky_solar",
    "coalesce_phase",
    "compose_center",
    "cooling_effectiveness",
    "cooling_load",
    "cover_lever",
    "duty_decision",
    "energy_precool_decision",
    "estimate_rate",
    "fan_level",
    "fan_lever",
    "house_load_index",
    "in_window",
    "k_confidence",
    "merge_desired",
    "peak_window",
    "plan_run",
    "preset_lever",
    "reconcile",
    "return_decision",
    "return_eta",
    "return_lead_time",
    "rls_capacity_update",
    "rls_passive_update",
    "run_rest_durations",
    "schedule_precool",
    "seed_params",
    "select_regime",
    "simulate_room",
    "solar_curve_v2",
    "solar_forecast_curve",
    "solar_nowcast_bias",
    "switch_lever",
    "temperature_lever",
    "values_match",
]
